style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/maicol07/flarum_sso_php_plugin
options:
  #commits:
  # filters:
  #   Type:
  #     - feat
  #     - fix
  #     - perf
  #     - refactor
  commit_groups:
    sort_by: Custom
    title_order:
      - feat
      - update
      - perf
      - fix
      - refactor
      - style
      - build
      - chore
    title_maps:
      feat: ✨ Features
      fix: 🐛 Bug Fixes
      fixed: 🐛 Bug Fixes
      perf: ⚡ Performance Improvements
      refactor: ♻ Code Refactoring
      revert: ⏪ Reverted
      update: 🔄 Updates
      build: 👷 Building scripts changes
      chore: Other changes
      style: 🎨 Code styling
      docs: 📝 Documentation changes
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE